name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mobile_scanner: ^5.1.0
  geolocator: ^13.0.0
  url_launcher: ^6.3.1
  csv: ^6.0.0
  path_provider: ^2.1.2
  flutter_email_sender: ^6.0.1
  
  # Thư viện Firebase - Đã hạ xuống bản 3.x/5.x để khớp Dart 3.6.0
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.1.0
  firebase_database: ^11.1.0
  
  intl: ^0.19.0
  universal_html: ^2.3.0
  qr_flutter: ^4.1.0
  # Bản 2.2.5 là bản cao nhất hỗ trợ Dart < 3.9.0
  shared_preferences: ^2.2.5 

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Bản 3.0.0 tương thích tốt với Dart 3.6.0
  flutter_lints: ^3.0.0 

flutter:
  uses-material-design: true
  assets:
    - assets/logo1.png