name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Sửa dòng này để máy ảo dễ chấp nhận hơn

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mobile_scanner: ^5.1.0
  geolocator: ^13.0.0
  url_launcher: ^6.3.1
  csv: ^6.0.0
  path_provider: ^2.1.2
  flutter_email_sender: ^6.0.1
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_database: ^12.1.1
  intl: ^0.20.2
  universal_html: ^2.3.0
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo1.png