name: Flutter iOS Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'
          channel: 'stable'
          cache: true

      - name: Build Preparation
        run: |
          flutter pub get
          flutter build ios --config-only --simulator --no-codesign
          
          # TẠO LẠI FILE REGISTRANT TỪ ĐẦU (Nuclear Option)
          cat <<EOF > ios/Runner/GeneratedPluginRegistrant.m
          #import "GeneratedPluginRegistrant.h"

          // Import trực tiếp từ đường dẫn Framework
          #import <cloud_firestore/FLTFirebaseFirestorePlugin.h>
          #import <firebase_auth/FLTFirebaseAuthPlugin.h>
          #import <firebase_core/FLTFirebaseCorePlugin.h>
          #import <firebase_database/FLTFirebaseDatabasePlugin.h>
          #import <geolocator_apple/GeolocatorPlugin.h>
          #import <mobile_scanner/MobileScannerPlugin.h>
          #import <shared_preferences_foundation/FLTSharedPreferencesPlugin.h>
          #import <url_launcher_ios/FLTUrlLauncherPlugin.h>

          @implementation GeneratedPluginRegistrant

          + (void)registerWithRegistry:(NSObject<FlutterPluginRegistry>*)registry {
            [FLTFirebaseFirestorePlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTFirebaseFirestorePlugin"]];
            [FLTFirebaseAuthPlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTFirebaseAuthPlugin"]];
            [FLTFirebaseCorePlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTFirebaseCorePlugin"]];
            [FLTFirebaseDatabasePlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTFirebaseDatabasePlugin"]];
            [GeolocatorPlugin registerWithRegistrar:[registry registrarForPlugin:@"GeolocatorPlugin"]];
            [MobileScannerPlugin registerWithRegistrar:[registry registrarForPlugin:@"MobileScannerPlugin"]];
            [FLTSharedPreferencesPlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTSharedPreferencesPlugin"]];
            [FLTUrlLauncherPlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTUrlLauncherPlugin"]];
          }

          @end
          EOF
          
          cd ios
          pod install --repo-update

      - name: Build iOS for Simulator
        run: |
          # Dùng --no-pub để bảo vệ file .m đã vá
          flutter build ios --simulator --no-codesign --no-pub
      - name: Zip App
        run: |
          cd build/ios/iphonesimulator
          zip -r BVVCSEC_Final.zip Runner.app

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-file
          path: build/ios/iphonesimulator/BVVCSEC_Final.zip