name: Flutter iOS Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'
          channel: 'stable'
          cache: true

      - name: Build Preparation
        run: |
          flutter pub get
          flutter build ios --config-only --simulator --no-codesign
          
          cd ios
          # VÁ FILE: Chuyển về định dạng #import "File.h" 
          # Cách này giúp Xcode tìm thấy Header thông qua HEADER_SEARCH_PATHS đã cài ở trên
          sed -i '' 's/@import cloud_firestore;/#import "FLTFirebaseFirestorePlugin.h"/g' Runner/GeneratedPluginRegistrant.m || true
          sed -i '' 's/@import firebase_core;/#import "FLTFirebaseCorePlugin.h"/g' Runner/GeneratedPluginRegistrant.m || true
          
          pod install --repo-update

      - name: Build iOS for Simulator
        run: |
          # Dùng --no-pub để bảo vệ file .m đã vá
          flutter build ios --simulator --no-codesign --no-pub
      - name: Zip App
        run: |
          cd build/ios/iphonesimulator
          zip -r BVVCSEC_Final.zip Runner.app

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-file
          path: build/ios/iphonesimulator/BVVCSEC_Final.zip