name: Flutter iOS Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'
          channel: 'stable'
          cache: true

      - name: Build Preparation
        run: |
          flutter pub get
          flutter clean
          # Xóa sạch cache Pods cũ trên máy ảo
          cd ios
          rm -rf Pods Podfile.lock Runner/GeneratedPluginRegistrant.* pod install --repo-update
          cd ..

      - name: Build iOS for Simulator
        run: |
          # Build bình thường, không dùng --no-pub để Flutter tự tạo lại file Registrant chuẩn
          flutter build ios --simulator --no-codesign

      - name: Zip App
        run: |
          cd build/ios/iphonesimulator
          zip -r BVVCSEC_Final.zip Runner.app

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-file
          path: build/ios/iphonesimulator/BVVCSEC_Final.zip