name: Flutter iOS Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'
          channel: 'stable'
          cache: true

      - name: Build Preparation
        run: |
          flutter pub get
          flutter build ios --config-only --simulator --no-codesign
          
          cd ios
          # XÓA TOÀN BỘ CÁC DÒNG @IMPORT VÀ THAY BẰNG #IMPORT CỔ ĐIỂN
          # Cách này tránh việc Xcode cố tìm Module mà chỉ tìm File .h đơn thuần
          sed -i '' 's/@import cloud_firestore;/#import "FLTFirebaseFirestorePlugin.h"/g' Runner/GeneratedPluginRegistrant.m || true
          sed -i '' 's/@import firebase_core;/#import "FLTFirebaseCorePlugin.h"/g' Runner/GeneratedPluginRegistrant.m || true
          sed -i '' 's/@import firebase_auth;/#import "FLTFirebaseAuthPlugin.h"/g' Runner/GeneratedPluginRegistrant.m || true
          sed -i '' 's/@import firebase_database;/#import "FLTFirebaseDatabasePlugin.h"/g' Runner/GeneratedPluginRegistrant.m || true
          
          # Cài đặt lại Pods với repo mới nhất
          pod install --repo-update

      - name: Build iOS for Simulator
        run: |
          # Dùng --no-pub để bảo vệ file .m đã vá
          flutter build ios --simulator --no-codesign --no-pub
      - name: Zip App
        run: |
          cd build/ios/iphonesimulator
          zip -r BVVCSEC_Final.zip Runner.app

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-file
          path: build/ios/iphonesimulator/BVVCSEC_Final.zip