name: Flutter iOS Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'
          channel: 'stable'
          cache: true

      - name: Build Preparation
        run: |
          flutter pub get
          flutter clean
          flutter build ios --config-only --simulator --no-codesign
          
          cd ios
          # Vá file Registrant về định dạng Header chuẩn
          sed -i '' 's/@import cloud_firestore;/#import <cloud_firestore\/FLTFirebaseFirestorePlugin.h>/g' Runner/GeneratedPluginRegistrant.m || true
          sed -i '' 's/@import firebase_core;/#import <firebase_core\/FLTFirebaseCorePlugin.h>/g' Runner/GeneratedPluginRegistrant.m || true
          sed -i '' 's/@import firebase_auth;/#import <firebase_auth\/FLTFirebaseAuthPlugin.h>/g' Runner/GeneratedPluginRegistrant.m || true
          sed -i '' 's/@import firebase_database;/#import <firebase_database\/FLTFirebaseDatabasePlugin.h>/g' Runner/GeneratedPluginRegistrant.m || true
          
          pod install --repo-update

      - name: Build iOS for Simulator
        run: |
          flutter build ios --simulator --no-codesign --no-pub
      - name: Zip App
        run: |
          cd build/ios/iphonesimulator
          zip -r BVVCSEC_Final.zip Runner.app

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-file
          path: build/ios/iphonesimulator/BVVCSEC_Final.zip