name: Flutter iOS Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # Đã bỏ dòng flutter-version để tự lấy bản mới nhất

      - name: Install Dependencies
        run: |
          flutter pub get
          cd ios && pod install

      - name: Build iOS for Simulator
        run: |
          flutter build ios --simulator --no-codesign
          
      - name: Zip App
        run: |
          cd build/ios/iphonesimulator
          zip -r BVVCSEC_ios.zip Runner.app

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-file
          path: build/ios/iphonesimulator/BVVCSEC_ios.zip