name: Flutter iOS Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Tự động lấy bản Flutter mới nhất hiện tại

      - name: Install Dependencies
        run: |
          flutter pub get
          # Thêm lệnh này để Flutter tự tạo lại các file liên kết còn thiếu
          flutter precache --ios
          cd ios
          pod install --repo-update

      - name: Build iOS for Simulator
        run: |
          flutter build ios --simulator --no-codesign
          
      - name: Zip App
        run: |
          cd build/ios/iphonesimulator
          # Đổi tên file zip xuất ra thành BVVCSEC
          zip -r BVVCSEC_Final.zip Runner.app

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-file
          path: build/ios/iphonesimulator/BVVCSEC_Final.zip