name: Flutter iOS Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Tự động lấy bản mới nhất để không bị lỗi version

      - name: Install Dependencies
        run: |
          flutter pub get
          cd ios && pod install

      - name: Build iOS for Simulator
        run: |
          flutter build ios --simulator --no-codesign
          
      - name: Zip App
        run: |
          cd build/ios/iphonesimulator
          # Lệnh này sẽ nén app với tên bạn muốn
          zip -r BVVCSEC_Final.app.zip Runner.app

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-file
          path: build/ios/iphonesimulator/BVVCSEC_Final.app.zip