name: Flutter iOS Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'
          channel: 'stable'
          cache: true

      - name: Build Preparation
        run: |
          flutter clean
          flutter pub get
          flutter build ios --config-only --simulator --no-codesign
          
          cd ios
          # TRẢ VỀ NGUYÊN BẢN: Nếu bạn lỡ vá file trước đó, hãy xóa sạch các dòng vá cũ
          # Để file GeneratedPluginRegistrant.m ở dạng mặc định của Flutter
          # Nếu vẫn bị lỗi 'Module not found', hãy thử dòng dưới đây:
          sed -i '' 's/@import cloud_firestore;/#import <cloud_firestore\/FLTFirebaseFirestorePlugin.h>/g' Runner/GeneratedPluginRegistrant.m || true
          
          rm -rf Pods Podfile.lock
          pod install --repo-update

      - name: Build iOS for Simulator
        run: |
          flutter build ios --simulator --no-codesign

      - name: Zip App
        run: |
          cd build/ios/iphonesimulator
          zip -r BVVCSEC_Final.zip Runner.app

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-file
          path: build/ios/iphonesimulator/BVVCSEC_Final.zip