name: Flutter iOS Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'
          channel: 'stable'
          cache: true

      - name: Build Preparation
        run: |
          flutter pub get
          flutter clean
          # Tạo config trước để có thư mục ios/Flutter
          flutter build ios --config-only --simulator --no-codesign
          cd ios
          # Xóa cache cũ nếu có để tránh xung đột module
          rm -rf Pods Podfile.lock
          pod install --repo-update

      - name: Build iOS for Simulator
        run: |
          # Dùng --no-pub để giữ nguyên các file cấu hình đã được pod install xử lý
          flutter build ios --simulator --no-codesign --no-pub

      - name: Zip App
        run: |
          cd build/ios/iphonesimulator
          zip -r BVVCSEC_Final.zip Runner.app

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-file
          path: build/ios/iphonesimulator/BVVCSEC_Final.zip