name: Flutter iOS Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build Preparation
        run: |
          flutter pub get
          flutter clean
          flutter build ios --config-only --simulator --no-codesign
          cd ios
          # Lệnh 'hack': Chuyển @import sang #import trong file Registrant
          sed -i '' 's/@import cloud_firestore;/#import <cloud_firestore\/FLTFirebaseFirestorePlugin.h>/g' Runner/GeneratedPluginRegistrant.m || true
          pod install --repo-update

      - name: Build iOS for Simulator
        run: |
          # Chạy build với lệnh chi tiết hơn
          flutter build ios --simulator --no-codesign --verbose
          
      - name: Zip App
        run: |
          cd build/ios/iphonesimulator
          zip -r BVVCSEC_Final.zip Runner.app

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-file
          path: build/ios/iphonesimulator/BVVCSEC_Final.zip