name: Flutter iOS Build
on:
  workflow_dispatch: # Cho phép bạn bấm nút chạy thủ công trên web

jobs:
  build:
    runs-on: macos-latest # Mượn máy Mac của GitHub
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.19.0' # Hoặc phiên bản bạn đang dùng

      - name: Install Dependencies
        run: flutter pub get

      - name: Build iOS for Simulator
        run: |
          flutter build ios --simulator --no-codesign
          
      - name: Zip App
        run: |
          cd build/ios/iphonesimulator
          zip -r BVVCSEC_ios.zip Runner.app

      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-file
          path: build/ios/iphonesimulator/BVVCSEC_ios.zip