name: Flutter iOS Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build Preparation
        run: |
          flutter pub get
          # Quan trọng: Tạo file cấu hình và liên kết module TRƯỚC khi build
          flutter build ios --config-only --simulator --no-codesign
          cd ios
          pod install --repo-update

      - name: Build iOS for Simulator
        run: |
          # Build thực tế sau khi đã có đầy đủ cấu hình Pods
          flutter build ios --simulator --no-codesign
          
      - name: Zip App
        run: |
          cd build/ios/iphonesimulator
          zip -r BVVCSEC_Final.zip Runner.app

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-file
          path: build/ios/iphonesimulator/BVVCSEC_Final.zip