name: Flutter iOS Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build Preparation
        run: |
          flutter pub get
          flutter clean
          # Xóa sạch dấu vết cũ trên máy ảo
          cd ios
          rm -rf Pods Podfile.lock .symlinks Runner/GeneratedPluginRegistrant.*
          cd ..
          # Tạo lại cấu hình sạch
          flutter build ios --config-only --simulator --no-codesign
          cd ios
          pod install --repo-update

      - name: Build iOS for Simulator
        run: |
          # Dùng lệnh verbose để xem chi tiết nếu vẫn lỗi
          flutter build ios --simulator --no-codesign
          
      - name: Zip App
        run: |
          cd build/ios/iphonesimulator
          zip -r BVVCSEC_Final.zip Runner.app

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-file
          path: build/ios/iphonesimulator/BVVCSEC_Final.zip